"""third Migration

Revision ID: 7d440c6097c2
Revises: d1d4d724b46a
Create Date: 2021-03-30 17:23:00.189905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d440c6097c2'
down_revision = 'd1d4d724b46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog', sa.String(), nullable=True))
    op.drop_column('blogs', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'blog')
    # ### end Alembic commands ###
